CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "phone" varchar(20),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "user_id" INT UNIQUE NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);